name: "test1"
on:
  push:
    branches:
      - main
jobs:
  lint-test-coverage:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
          